In [12]:
# Find the index of the 5th repetition of number 1 in x= np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
import numpy as np
x= np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
z=np.where(x==1)[0]
print(z)
if  len(z)>=5:
    print(z[4])
else:
    print("false")

[ 0  2  3  7  8 10 11]
8


In [14]:
#Compute the Euclidean distance between two arrays a = np.array([1,2,3]) b = np.array([4,5,6])
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
distance = np.sqrt(np.sum((a - b) ** 2))
print(distance)

5.196152422706632


In [17]:
#Replace all odd numbers in the array with-1 without changing the array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr = np.where(arr % 2 != 0, -1, arr)
print(new_arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [18]:
# From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
a = np.array([5, 15, 25, 35, 45])
new_a = np.clip(a, 10, 30)
print(new_a)

[10 15 25 30 30]


In [20]:
# Create a 4*4 matrix with entries from uniform distribution data in the interval 10 to 20. Normalize the matrix so that the minimum has a value of 0 and the maximum has a value of 1
matrix = np.random.uniform(10, 20, (4, 4))
print(matrix)
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(normalized_matrix)

[[12.4120376  15.18258623 17.96964078 15.67500589]
 [13.83758155 13.58821833 11.91065176 10.91969745]
 [13.56861941 14.90623018 10.53653705 10.99002308]
 [18.35674099 18.73462063 17.89207141 14.49884351]]
[[0.22877305 0.56672381 0.90668797 0.62678903]
 [0.40266051 0.37224325 0.16761414 0.0467378 ]
 [0.36985258 0.53301398 0.         0.0553161 ]
 [0.95390634 1.         0.89722608 0.48332106]]


In [21]:
#Find the mean, median, and standard deviation of a 1-d array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(arr)
print(mean)
median = np.median(arr)
print(median)
std_dev = np.std(arr)
print(std_dev)

5.5
5.5
2.8722813232690143


In [22]:
#Get all items between 5 and 10 from a. Input: a= [2, 6, 1, 9, 10, 3, 27].
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 6  9 10]


In [23]:
#Convert a 1D array to a 2D array with 2 rows.
arr = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [25]:
#Create a 2D array and swap the first two rows and two columns.
# Create a 2D array
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print(arr)
# Swap the first two rows
arr[[0, 1]] = arr[[1, 0]]
print(arr)
# Swap the first two columns
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  5  7  8]
 [ 2  1  3  4]
 [10  9 11 12]
 [14 13 15 16]]


In [27]:
#Find the most frequent values in an array of positive integers. The original array is [6 9 5 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6 3 4 5 9 7 2 7 0 2 2 6 ].
import numpy as np
from collections import Counter
arr = np.array([6, 9, 5, 1, 7, 5, 1, 0, 1, 5, 5, 0, 8, 9, 0, 7, 0, 7, 6, 5, 
                1, 1, 9, 5, 3, 8, 7, 9, 6, 3, 4, 5, 9, 7, 2, 7, 0, 2, 2, 6])
counts = Counter(arr)
print(counts)
max_freq = max(counts.values())
print(max_freq)
most_frequent = [key for key, value in counts.items() if value == max_freq]
print(most_frequent)

Counter({np.int64(5): 7, np.int64(7): 6, np.int64(9): 5, np.int64(1): 5, np.int64(0): 5, np.int64(6): 4, np.int64(2): 3, np.int64(8): 2, np.int64(3): 2, np.int64(4): 1})
7
[np.int64(5)]


In [28]:
# Create a symmetric matrix of order 4*4, whose items are taken from a standard normal distribution.
random_matrix = np.random.randn(4, 4)
print(random_matrix)
symmetric_matrix = (random_matrix + random_matrix.T) / 2
print(symmetric_matrix)

[[-0.39809503  0.29936854  0.89272251  1.24660154]
 [-0.41061269  0.65555429  0.51862351  0.36415695]
 [-0.30608766  0.44244732 -0.46007476  1.15365748]
 [-0.04927789  0.83136568  1.59982661  0.85216489]]
[[-0.39809503 -0.05562207  0.29331742  0.59866182]
 [-0.05562207  0.65555429  0.48053542  0.59776132]
 [ 0.29331742  0.48053542 -0.46007476  1.37674204]
 [ 0.59866182  0.59776132  1.37674204  0.85216489]]


In [29]:
# Compute the cross product of two 3*3 matrices
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(A)
B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])
print(B)
cross_product = np.cross(A, B)
print(cross_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [30]:
#Write a NumPy program to sort the student id with increasing height of the students from the given student id and height. Print the integer indices that describe the sort order by multiple columns and the sorted data.
student_data = np.array([
    [101, 160],  
    [102, 165],
    [103, 162],
    [104, 160],
    [105, 170]
])
student_ids = student_data[:, 0]
heights = student_data[:, 1]
sort_indices = np.lexsort((student_ids, heights))#sort by height
print(sort_indices)
sorted_data = student_data[sort_indices]
print(sorted_data)



[0 3 2 1 4]
[[101 160]
 [104 160]
 [103 162]
 [102 165]
 [105 170]]


In [31]:
# Return array of odd rows and even columns from below numpy array :
x= np.array([[3, 6, 9, 12], 
             [15, 18, 21, 24], 
             [27, 30, 33, 36], 
             [39, 42, 45, 48],
             [51, 54, 57, 60]])
result = x[::2, 1::2]#rows(1st,3rd,5th index=0,2,4)columns(2,4 index=1,3)
print(result)

[[ 6 12]
 [30 36]
 [54 60]]


In [32]:
#Calculate the sum of all rows and columns of a 2-D NumPy array.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row_sums = np.sum(arr, axis=1)
print(row_sums)
column_sums = np.sum(arr, axis=0)
print(column_sums)

[ 6 15 24]
[12 15 18]


In [33]:
# Write a code to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
result = np.dot(A, B)
print(result)

[[1.0682181  1.04907195]
 [1.2346786  1.12453143]
 [1.47097268 1.20541263]
 [1.09964568 1.03849027]
 [0.9346283  0.78910742]]


In [34]:
#Write a code to find the roots of the polynomials x2 − 4x + 7 = 0.
coefficients = [1, -4, 7]
roots = np.roots(coefficients)
print(roots)

[2.+1.73205081j 2.-1.73205081j]


In [35]:
# Write a code to create a 5x5 array with random values and normalize it row-wise.
arr = np.random.rand(5, 5)
row_min = arr.min(axis=1).reshape(-1, 1)  # Minimum value of each row
row_range = arr.max(axis=1).reshape(-1, 1) - row_min  # Range (max - min) for each row
normalized_arr = (arr - row_min) / row_range  # Normalize each row
print(arr)
print(normalized_arr)

[[0.67328412 0.75131149 0.37906107 0.1985814  0.61836286]
 [0.62226343 0.53812415 0.42819316 0.81267806 0.5640633 ]
 [0.28538281 0.97825491 0.74385816 0.2822946  0.34767255]
 [0.02968677 0.49095524 0.37790228 0.53366228 0.25635918]
 [0.95186166 0.31542533 0.31434577 0.44739183 0.94477295]]
[[0.85883278 1.         0.32652405 0.         0.75946917]
 [0.50475394 0.28591757 0.         1.         0.35338225]
 [0.00443735 1.         0.66320386 0.         0.0939392 ]
 [0.         0.9152597  0.69093737 1.         0.4497687 ]
 [1.         0.00169338 0.         0.2086945  0.98888073]]


In [36]:
#Write a NumPy program to create a 9*9*2 array with random values and extract any array of shape (5,5,2) from the said array.
arr = np.random.rand(9, 9, 2)
print(arr)
# Extract a sub-array of shape (5, 5, 2) from the original array
# For example, extract from indices 2 to 6 (inclusive for rows and columns)
sub_array = arr[2:7, 2:7, :]
print(sub_array)

[[[0.81498627 0.84223161]
  [0.18515899 0.94034286]
  [0.91281119 0.21394062]
  [0.85602873 0.68947043]
  [0.52225192 0.75653144]
  [0.27057956 0.5408713 ]
  [0.95857978 0.78951997]
  [0.66627856 0.05008769]
  [0.27128595 0.84699705]]

 [[0.84126567 0.64311758]
  [0.37097749 0.93359374]
  [0.58007261 0.75197139]
  [0.32662194 0.11350136]
  [0.79311864 0.29005431]
  [0.35965255 0.98612846]
  [0.38038046 0.40090456]
  [0.08125478 0.67259645]
  [0.27060834 0.13289647]]

 [[0.79880757 0.84732184]
  [0.93073429 0.08410987]
  [0.85224452 0.78870875]
  [0.94020798 0.53358415]
  [0.01288484 0.52591265]
  [0.57495435 0.52624613]
  [0.07819696 0.33683471]
  [0.45087011 0.88391668]
  [0.42520118 0.91716018]]

 [[0.38922754 0.06241441]
  [0.64294113 0.2682199 ]
  [0.41197362 0.68876952]
  [0.72869018 0.85496796]
  [0.58803774 0.07163601]
  [0.49230285 0.78109758]
  [0.05639473 0.46770714]
  [0.09139958 0.46809774]
  [0.9801897  0.71896322]]

 [[0.69623106 0.97258202]
  [0.07498909 0.5154732 ]
  [0

In [37]:
# Write a code to create a 4*4 array with random values and sort each column
arr = np.random.rand(4, 4)
print(arr)
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)

[[0.29655907 0.34348956 0.83806766 0.01954696]
 [0.49664886 0.69418273 0.08182499 0.44633287]
 [0.26515849 0.66246529 0.83625789 0.49684558]
 [0.24237101 0.89669305 0.88473107 0.37006212]]
[[0.24237101 0.34348956 0.08182499 0.01954696]
 [0.26515849 0.66246529 0.83625789 0.37006212]
 [0.29655907 0.69418273 0.83806766 0.44633287]
 [0.49664886 0.89669305 0.88473107 0.49684558]]


In [ ]:
#In a cricket match, a batsman scores any one of {1,2,3,4,6,0}. When he scores 0, it will be considered as ”OUT”. If he will face 50 balls maximum, then find the score that he will make before getting”OUT”. Draw the plot of the run scored by the batsman.
