In [1]:
import numpy as np


In [2]:
L=np.arange(1000000)
M=list(range(1000000))
%timeit L1=L*2

2.86 ms ± 448 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit M1=[x*2 for x in M]

82.5 ms ± 8.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
from datetime import datetime as dt
now1=dt.now()
M1=[x*2 for x in M]
now2=dt.now()
print(now2-now1)

0:00:00.071195


In [6]:
data=np.array([1.5,-0.1,3])
print(data,"and its type is",type(data))

[ 1.5 -0.1  3. ] and its type is <class 'numpy.ndarray'>


In [8]:
#difference datatype converted to same
data=np.array(['hello',1])
print(data)

['hello' '1']


In [12]:
data=np.array([[1,2,6.5],['hello',4.7,'iter']])
print(data)

[['1' '2' '6.5']
 ['hello' '4.7' 'iter']]


In [13]:
#number of dimesnsion of an array
data.ndim

2

In [14]:
#number of element in each dimension
data.shape

(2, 3)

In [16]:
#create arrays of o's and 1's
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
x=np.zeros((3,6))
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
#create array without initializing its value
np.empty((2,3,2))

array([[[1.45331575e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.77605619e+160]],

       [[6.11385377e+169, 5.19414792e+170],
        [3.37673742e-057, 2.62149888e+180],
        [1.36900562e-071, 2.49172993e+180]]])

In [23]:
#returns ndaray instead of list
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(10,20,5)

array([10, 15])

In [25]:
#create an array of evenly spaced numbers within a specified range
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [26]:
#numpy.full(shape, fill value)
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [27]:
#eye/identity(1's on diagonal and o's at rest)
s=np.identity(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
s=np.eye(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
s=np.eye(4,k=1)
s

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [34]:
#converting datatype
s=np.array([1,2,3],dtype=np.float64)
t=np.array([1,2,3],dtype=np.int32)
print('s',s,'\n','t',t)

s [1. 2. 3.] 
 t [1 2 3]


In [37]:
print(s.dtype)
print(t.dtype)

float64
int32


In [38]:
s=np.array([1,2,3,4,5])
print(s,s.dtype)

[1 2 3 4 5] int64


In [40]:
s=s.astype(np.float64)
print(s,s.dtype)

[1. 2. 3. 4. 5.] float64


In [42]:
#arithmetic operation
s=np.array([[1,2,3],[4,5,6]]);s


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
t=np.array([[1,1,1],[2,2,2]]);t

array([[1, 1, 1],
       [2, 2, 2]])

In [44]:
s+t

array([[2, 3, 4],
       [6, 7, 8]])

In [45]:
s*t

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [46]:
7*t

array([[ 7,  7,  7],
       [14, 14, 14]])

In [47]:
t**2

array([[1, 1, 1],
       [4, 4, 4]])

In [48]:
7/t

array([[7. , 7. , 7. ],
       [3.5, 3.5, 3.5]])

In [49]:
#comparison between arrays give boolean arrays
s>t

array([[False,  True,  True],
       [ True,  True,  True]])

In [51]:
# Create an ndarray object with float data type. Convert this to integerdata type. Observe the changes in the dat

# Create an ndarray with float data type
a = np.array([1.1, 2.5, 3.9, 4.7], dtype=float)
print(a)

# Convert the float array to integer data type
b = a.astype(int)
print(b)

Original array with float data type:
[1.1 2.5 3.9 4.7]

Array converted to integer data type:
[1 2 3 4]


In [52]:
# Create the identity matrix of order 4
identity_matrix = np.eye(4)
print("Identity Matrix:")
print(identity_matrix)

# Create the matrix with sub-diagonal and super-diagonal elements as 1
matrix_with_diagonals = np.eye(4, k=1) + np.eye(4, k=-1)
print("\nMatrix with Sub-diagonal and Super-diagonal elements as 1:")
print(matrix_with_diagonals)

# Compare the elements of the two matrices
comparison = identity_matrix == matrix_with_diagonals
print("\nComparison of elements (True if equal):")
print(comparison)

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matrix with Sub-diagonal and Super-diagonal elements as 1:
[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]

Comparison of elements (True if equal):
[[False False  True  True]
 [False False False  True]
 [ True False False False]
 [ True  True False False]]


In [2]:
#indexing and slicing
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print (arr[5])

5


In [4]:
print(arr[5:8])

[5 6 7]


In [5]:
arr[5]=6
arr

array([0, 1, 2, 3, 4, 6, 6, 7, 8, 9])

In [6]:
arr[5:8]=10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
arr[::2]=1000
arr

array([1000,   20, 1000,   40, 1000,   60, 1000,   80])

In [8]:
arr = np.array([1000, 20, 1000, 40, 1000, 60, 1000, 80])
rev=arr[::-1]
print(rev)

[  80 1000   60 1000   40 1000   20 1000]


In [9]:
arr=np.array([1,2,3,4,5])
a=arr[0:2].copy()
arr[0:3]=5
a

array([1, 2])

In [10]:
b=np.array([[0,0.1,0.2,0.3,0.4],
           [1,1.1,1.2,1.3,1.4],
           [2,2.1,2.2,2.3,2.4],
           [3,3.1,3.2,3.3,3.4],
           [4,4.1,4.2,4.3,4.4]])
print(b[1,2])
print(b[1][2])

1.2
1.2


In [11]:
b[0:2]

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [1. , 1.1, 1.2, 1.3, 1.4]])

In [12]:
b[0:2,2]

array([0.2, 1.2])

In [13]:
b[0:2]

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [1. , 1.1, 1.2, 1.3, 1.4]])

In [14]:
b[:,0:2]

array([[0. , 0.1],
       [1. , 1.1],
       [2. , 2.1],
       [3. , 3.1],
       [4. , 4.1]])

In [15]:
b[:,:]

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [2. , 2.1, 2.2, 2.3, 2.4],
       [3. , 3.1, 3.2, 3.3, 3.4],
       [4. , 4.1, 4.2, 4.3, 4.4]])

In [16]:
b[1][0:2]

array([1. , 1.1])

In [17]:
b[0]=17
b

array([[17. , 17. , 17. , 17. , 17. ],
       [ 1. ,  1.1,  1.2,  1.3,  1.4],
       [ 2. ,  2.1,  2.2,  2.3,  2.4],
       [ 3. ,  3.1,  3.2,  3.3,  3.4],
       [ 4. ,  4.1,  4.2,  4.3,  4.4]])

In [18]:
b[0][0:3]=7
b

array([[ 7. ,  7. ,  7. , 17. , 17. ],
       [ 1. ,  1.1,  1.2,  1.3,  1.4],
       [ 2. ,  2.1,  2.2,  2.3,  2.4],
       [ 3. ,  3.1,  3.2,  3.3,  3.4],
       [ 4. ,  4.1,  4.2,  4.3,  4.4]])

In [19]:
b[0,3]=90
b

array([[ 7. ,  7. ,  7. , 90. , 17. ],
       [ 1. ,  1.1,  1.2,  1.3,  1.4],
       [ 2. ,  2.1,  2.2,  2.3,  2.4],
       [ 3. ,  3.1,  3.2,  3.3,  3.4],
       [ 4. ,  4.1,  4.2,  4.3,  4.4]])

In [20]:
b[0,4]=90
b

array([[ 7. ,  7. ,  7. , 90. , 90. ],
       [ 1. ,  1.1,  1.2,  1.3,  1.4],
       [ 2. ,  2.1,  2.2,  2.3,  2.4],
       [ 3. ,  3.1,  3.2,  3.3,  3.4],
       [ 4. ,  4.1,  4.2,  4.3,  4.4]])

In [21]:
names=np.array(["a","b","c","a","a"])
names=="a"

array([ True, False, False,  True,  True])

In [22]:
numbers=np.array([1,2,3,4,5])
numbers[names=="a"]

array([1, 4, 5])

In [23]:
names=np.array(["a","b","c","a","a"])
names!="a"


array([False,  True,  True, False, False])

In [24]:
numbers=np.array([1,2,3,4,5])
numbers[names!="a"]

array([2, 3])

In [25]:
names=np.array(["a","b","c","a","a"])
reg=np.array([1,2,3,4,5])
cond=(names=="b")|(names=="c")
reg[cond]

array([2, 3])

In [26]:
#reshaping array
a=np.array([[1,2,3],[7,3,4]])
a

array([[1, 2, 3],
       [7, 3, 4]])

In [27]:
a.ravel()

array([1, 2, 3, 7, 3, 4])

In [28]:
a.reshape(3,2)

array([[1, 2],
       [3, 7],
       [3, 4]])

In [29]:
a.T

array([[1, 7],
       [2, 3],
       [3, 4]])

In [30]:
#fancy indexing
a=np.array([100,200,300,400,500,600,700])
selected=a[[1,2,5,6]]
selected

array([200, 300, 600, 700])

In [31]:
a=np.zeros((8,4))
for i in range(8):
    a[i]=i
a

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [32]:
a[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [33]:
a[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [34]:
#random numbers
np.random.rand(2,3)

array([[0.90515862, 0.52783337, 0.63862946],
       [0.46139903, 0.57752078, 0.63614968]])

In [35]:
np.random.randint(1,5,(2,3))

array([[4, 4, 4],
       [3, 2, 1]], dtype=int32)

In [37]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [41]:
#unique values
ints=np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)


array([1, 2, 3, 4])

In [44]:
v=np.array([6,0,0,3,2,5,6])
np.isin(v,[2,3,6])


array([ True, False, False,  True,  True, False,  True])

In [45]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 7, 8])

result = np.isin(array1, array2)
print(result)

[False False  True  True False]


In [46]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([3, 4, 5, 6])

result = np.setxor1d(array1, array2)
print(result) 

[1 2 5 6]


In [47]:
x=np.array([[1,2,3,],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])